Add missing import
uranusjr/django-tutorial-for-programmers pull request #34
Opened 2017-06-25 03:30 UTC by yen3

If I follow the instruction to add the url rule (`url(r'^store/', include('stores.urls')),`) and run test, the test would tell it does not know how `include` it is. Just import `include` function to resolve the problem.

2017-06-25 05:19 UTC, uranusjr commented
這是因為 Django 修改了 `admin.site.urls` 的寫法 (應該是在 1.9？)，原本那行是 `url(r'^admin/`, include(admin.site.urls))`，所以預設 `urls.py` 本來就有 import `include`。

改寫成這樣會比較好：

請確認在 `lunch/urls.py` 的開頭有 import `include`

```python
from django.conf.urls import include, url
```

2017-06-25 05:20 UTC, uranusjr requested changes
這是因為 Django 修改了 `admin.site.urls` 的寫法。

在較舊的版本裡 (這份教學是根據 Django 1.8，請看 branch 名) `urlpatterns` 的第一項是

```python
url(r'^admin/', include(admin.site.urls))
```

所以 `urls.py` 本來就有 import `include`。

改寫成這樣會比較好：

----

請確認在 `lunch/urls.py` 的開頭有 import `include`

```python
from django.conf.urls import include, url
```

----

2017-07-02 07:48 UTC, yen3 commented
好的，感謝你的回應

2017-07-02 09:46 UTC, uranusjr commented
如果方便可以幫忙在這個 PR 改一下，我就可以直接 merge

2017-07-04 10:47 UTC, yen3 commented
你好，我試著修改，如果有問題再跟我說，謝謝。

2017-07-04 16:30 UTC, uranusjr approved these changes
👍

2017-07-04 16:31 UTC, merged